version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: meualuno
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret_password

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: meualuno
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret_password
    ports:
      - "3306:3306"

volumes:
  db_data:
